import { Ticker, News, AIRecommendation, CandleData } from '@/types';

function generateCandleData(basePrice: number, days: number): CandleData[] {
  const data: CandleData[] = [];
  let currentPrice = basePrice;
  const now = new Date();

  for (let i = days; i > 0; i--) {
    const timestamp = new Date(now.getTime() - i * 24 * 60 * 60 * 1000).getTime();
    const changePercent = (Math.random() - 0.5) * 0.04;
    const volatility = 1 + changePercent;

    const open = currentPrice;
    const close = currentPrice * volatility;
    const high = Math.max(open, close) * (1 + Math.random() * 0.01);
    const low = Math.min(open, close) * (1 - Math.random() * 0.01);

    data.push({
      timestamp,
      open,
      high,
      low,
      close,
      volume: Math.floor(Math.random() * 1e8) + 1e7,
    });

    currentPrice = close;
  }

  return data;
}

export const MOCK_TICKERS: Ticker[] = [
  {
    id: '1',
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 45234.50,
    change24h: 3.45,
    change7d: 12.34,
    change30d: 28.56,
    volume24h: 3.2e10,
    marketCap: 8.8e11,
    high24h: 45890,
    low24h: 43567,
    category: 'crypto',
    historicalData: generateCandleData(45234.50, 40),
  },
  {
    id: '2',
    symbol: 'ETH',
    name: 'Ethereum',
    price: 2456.78,
    change24h: -1.23,
    change7d: 5.67,
    change30d: 15.34,
    volume24h: 1.8e10,
    marketCap: 2.94e11,
    high24h: 2567,
    low24h: 2389,
    category: 'crypto',
    historicalData: generateCandleData(2456.78, 40),
  },
  {
    id: '3',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 189.45,
    change24h: 2.12,
    change7d: 3.45,
    change30d: 8.90,
    volume24h: 5.6e9,
    marketCap: 2.9e12,
    high24h: 190.23,
    low24h: 187.89,
    category: 'stock',
    historicalData: generateCandleData(189.45, 40),
  },
  {
    id: '4',
    symbol: 'EURUSD',
    name: 'EUR/USD',
    price: 1.0856,
    change24h: 0.45,
    change7d: 1.23,
    change30d: 2.34,
    volume24h: 1.2e12,
    marketCap: 0,
    high24h: 1.0912,
    low24h: 1.0823,
    category: 'forex',
    historicalData: generateCandleData(1.0856, 40),
  },
  {
    id: '5',
    symbol: 'GOLD',
    name: 'Gold Spot',
    price: 2015.30,
    change24h: 1.67,
    change7d: 0.89,
    change30d: 5.23,
    volume24h: 2.3e9,
    marketCap: 0,
    high24h: 2045,
    low24h: 1998,
    category: 'commodity',
    historicalData: generateCandleData(2015.30, 40),
  },
  {
    id: '6',
    symbol: 'NVDA',
    name: 'NVIDIA',
    price: 876.45,
    change24h: 5.23,
    change7d: 8.12,
    change30d: 45.67,
    volume24h: 3.2e9,
    marketCap: 2.14e12,
    high24h: 878.90,
    low24h: 834.56,
    category: 'stock',
    historicalData: generateCandleData(876.45, 40),
  },
  {
    id: '7',
    symbol: 'MSFT',
    name: 'Microsoft',
    price: 423.89,
    change24h: 1.34,
    change7d: 2.56,
    change30d: 12.34,
    volume24h: 2.1e9,
    marketCap: 3.15e12,
    high24h: 425.23,
    low24h: 420.45,
    category: 'stock',
    historicalData: generateCandleData(423.89, 40),
  },
  {
    id: '8',
    symbol: 'SOL',
    name: 'Solana',
    price: 145.67,
    change24h: 8.34,
    change7d: 23.45,
    change30d: -5.67,
    volume24h: 8.9e8,
    marketCap: 6.8e10,
    high24h: 156.78,
    low24h: 132.45,
    category: 'crypto',
    historicalData: generateCandleData(145.67, 40),
  },
];

export const MOCK_NEWS: News[] = [
  {
    id: '1',
    title: 'Bitcoin alcanza nuevo máximo histórico de $47K',
    description: 'La criptomoneda rompe resistencia tras aprobación de ETF spot',
    content: 'Bitcoin ha superado los $47,000 por primera vez en meses, impulsado por la aprobación de varios ETF spot en EE.UU.',
    source: 'CoinDesk',
    category: 'crypto',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    sentiment: 'positive',
    relatedTickers: ['BTC', 'ETH'],
  },
  {
    id: '2',
    title: 'La Fed mantiene tasas sin cambios en reunión de abril',
    description: 'Powell señala posible pausa en ciclo de alzas de tasas',
    content: 'La Reserva Federal decidió mantener las tasas de interés sin cambios, señalando una posible pausa en el ciclo de alzas.',
    source: 'Bloomberg',
    category: 'economy',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    sentiment: 'neutral',
    relatedTickers: ['EURUSD', 'AAPL', 'MSFT'],
  },
  {
    id: '3',
    title: 'NVIDIA reporta ganancias que superan expectativas',
    description: 'Impulsada por demanda de chips de IA',
    content: 'NVIDIA reportó ganancias trimestrales que superaron ampliamente las expectativas del mercado, impulsadas por la fuerte demanda de chips para inteligencia artificial.',
    source: 'Reuters',
    category: 'stocks',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    sentiment: 'positive',
    relatedTickers: ['NVDA'],
  },
  {
    id: '4',
    title: 'Ethereum 2.0 prepara nueva actualización importante',
    description: 'Dencun permitirá reducir costos de transacción en 90%',
    content: 'La próxima actualización de Ethereum promete reducir drásticamente los costos de gas en la red mediante el protocolo proto-danksharding.',
    source: 'CoinTelegraph',
    category: 'crypto',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    sentiment: 'positive',
    relatedTickers: ['ETH', 'SOL'],
  },
  {
    id: '5',
    title: 'Oro sube en busca de refugio seguro',
    description: 'Tensiones geopolíticas impulsan demanda de metales preciosos',
    content: 'El precio del oro ha subido ante las crecientes tensiones geopolíticas, con inversores buscando activos refugio.',
    source: 'MarketWatch',
    category: 'general',
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000),
    sentiment: 'neutral',
    relatedTickers: ['GOLD'],
  },
  {
    id: '6',
    title: 'Microsoft anuncia inversión masiva en IA',
    description: 'Invertirá $10 mil millones en infraestructura de IA',
    content: 'Microsoft anunció una inversión de $10 mil millones en infraestructura de inteligencia artificial, reforzando su posición en el sector.',
    source: 'Axios',
    category: 'stocks',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    sentiment: 'positive',
    relatedTickers: ['MSFT', 'NVDA'],
  },
];

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: '1',
    ticker: 'BTC',
    tickerName: 'Bitcoin',
    action: 'BUY',
    confidence: 92,
    targetPrice: 50000,
    stopLoss: 42000,
    entryPrice: 45234.50,
    analysis: 'Rompimiento de resistencia con volumen creciente. RSI en zona neutra pero con momentum positivo.',
    indicators: {
      rsi: 65,
      macd: 'Bullish crossover',
      movingAverage50: 44123,
      bollinger: 'Upper band breakout',
    },
    timeframe: '1d',
    timestamp: new Date(),
    aiModel: 'Advanced TrendAnalysis v2.1',
    risk: 'medium',
  },
  {
    id: '2',
    ticker: 'NVDA',
    tickerName: 'NVIDIA',
    action: 'BUY',
    confidence: 87,
    targetPrice: 950,
    stopLoss: 800,
    entryPrice: 876.45,
    analysis: 'Ganancias trimestrales impulsan nuevo máximo. Demanda de chips de IA sigue creciendo.',
    indicators: {
      rsi: 72,
      macd: 'Positive divergence',
      movingAverage50: 845,
      bollinger: 'Above upper band',
    },
    timeframe: '1w',
    timestamp: new Date(),
    aiModel: 'Fundamental + Technical Fusion',
    risk: 'medium',
  },
  {
    id: '3',
    ticker: 'ETH',
    tickerName: 'Ethereum',
    action: 'HOLD',
    confidence: 78,
    targetPrice: 2800,
    stopLoss: 2200,
    entryPrice: 2456.78,
    analysis: 'Consolidación dentro de rango. Esperar ruptura clara de resistencia en $2600.',
    indicators: {
      rsi: 55,
      macd: 'Neutral',
      movingAverage50: 2389,
      bollinger: 'Middle band',
    },
    timeframe: '4h',
    timestamp: new Date(),
    aiModel: 'Pattern Recognition AI',
    risk: 'low',
  },
  {
    id: '4',
    ticker: 'MSFT',
    tickerName: 'Microsoft',
    action: 'BUY',
    confidence: 84,
    targetPrice: 480,
    stopLoss: 400,
    entryPrice: 423.89,
    analysis: 'Inversión de $10B en IA es catalyst positivo. Earnings trajectory positiva.',
    indicators: {
      rsi: 68,
      macd: 'Positive',
      movingAverage50: 415,
      bollinger: 'Above middle band',
    },
    timeframe: '1d',
    timestamp: new Date(),
    aiModel: 'Catalyst Detection System',
    risk: 'low',
  },
  {
    id: '5',
    ticker: 'SOL',
    tickerName: 'Solana',
    action: 'SELL',
    confidence: 72,
    targetPrice: 120,
    stopLoss: 165,
    entryPrice: 145.67,
    analysis: 'Sobrecompra después de rally de 23% semanal. Divergencia en volumen. Tomar ganancias.',
    indicators: {
      rsi: 78,
      macd: 'Negative divergence',
      movingAverage50: 123,
      bollinger: 'Upper band',
    },
    timeframe: '4h',
    timestamp: new Date(),
    aiModel: 'Overbought Detector',
    risk: 'high',
  },
];
